CREATE DATABASE MONITOR;
USE MONITOR;

CREATE TABLE REGISTER(EMAIL VARCHAR(100) PRIMARY KEY NOT NULL, PASSWORD VARCHAR(20) NOT NULL);
SELECT * FROM REGISTER;

CREATE TABLE CREDENTIALS(EMAIL VARCHAR(20) REFERENCES REGISTER(EMAIL), PASSWORD VARCHAR(255)NOT NULL);
SELECT * FROM CREDENTIALS;

CREATE TABLE ACCOUNTS(ACCOUNT1 VARCHAR(20), PASS1 VARCHAR(20), ACCOUNT2 VARCHAR(20), PASS2 VARCHAR(20), ACCOUNT3 VARCHAR(20), PASS3 VARCHAR(20), ACCOUNT4 VARCHAR(20), PASS4 VARCHAR(20));
