CREATE DATABASE MONITOR;
USE MONITOR;

CREATE TABLE REGISTER(EMAIL VARCHAR(100) PRIMARY KEY NOT NULL, PASSWORD VARCHAR(20) NOT NULL);
SELECT * FROM REGISTER;

CREATE TABLE CREDENTIALS(EMAIL VARCHAR(20) REFERENCES REGISTER(EMAIL), PASSWORD VARCHAR(255)NOT NULL);
SELECT * FROM CREDENTIALS;